### PR TITLE
Fix unique ID

### PR DESCRIPTION
**Pull request by FFY00**

### CODE REVIEW

**Comment by FFY00** [comment]
Let's try to put a lock and see if it is more reliable.

**Comment by bentiss** [comment]
A lock won't help, you are between different processes

**Comment by FFY00** [comment]
Ah yes, sorry. I looked into it and the only way I think we are able to solve it is by writing a local pytest plugin to inject settings to the various nodes.

An alternative would be, instead of keeping a list, checking if the device exists on the system.

**Comment by bentiss** [comment]
> An alternative would be, instead of keeping a list, checking if the device exists on the system.

or use a wider range of possible unique ids so that the collision risk is minimal:
https://gitlab.freedesktop.org/libevdev/hid-tools/blob/master/hidtools/uhid.py#L168

And it's already there in `uhid.py`. You don't really need the name to be unique, because there is a HID property `uniq` used to report the serial number which is unique enough even across processes.

**Pull request merged**
