### PR TITLE
Trigger CI on pull requests

### PR DESCRIPTION
**Pull request by FFY00**

### CODE REVIEW

**Comment by FFY00** [comment]
It seems like this isn't enough.

**Comment by bentiss** [comment]
So, first, why I haven set `pull_request` in the gh-actions workflow: https://help.github.com/en/articles/events-that-trigger-workflows#pull-request-events-for-forked-repositories

But here, it seems that we should not attach the status message to the commit, but to the PR, so that's a different story.

The CI is run (see https://gitlab.freedesktop.org/bentiss/libratbag-tests/-/jobs/635939) we just fail at setting the correct status.

**Comment by FFY00** [comment]
Are we sure it that job was generated by a PR?

Looking at 'Trigger gitlab pipeline':

PR
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1049  100    27  100  1022    103   3915 --:--:-- --:--:-- --:--:--  4019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://developer.github.com/v3/repos/statuses/#create-a-status"
}
100   291  100   148  100   143   1193   1153 --:--:-- --:--:-- --:--:--  2346
```

Normal push
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2028  100   997  100  1031   1347   1393 --:--:-- --:--:-- --:--:--  2736
100  2028  100   997  100  1031   1347   1393 --:--:-- --:--:-- --:--:--  2736
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
{
  "url": "https://api.github.com/repos/libratbag/ratbag-emu/statuses/bf32c93c901b9052ede71f1f609b80f07eccc53f",
  "avatar_url": "https://avatars2.githubusercontent.com/in/15368?v=4",
  "id": 7697675696,
  "node_id": "MDEzOlN0YXR1c0NvbnRleHQ3Njk3Njc1Njk2",
  "state": "pending",
  "description": "Run pytest",
  "target_url": "https://gitlab.freedesktop.org/bentiss/libratbag-tests/pipelines/65102",
  "context": "Gitlab CI",
  "created_at": "2019-09-20T09:56:13Z",
  "updated_at": "2019-09-20T09:56:13Z",
  "creator": {
    "login": "github-actions[bot]",
    "id": 41898282,
100  1922  100  1711  100   211   4112    507 --:--:-- --:--:-- --:--:--  4620
    "node_id": "MDM6Qm90NDE4OTgyODI=",
    "avatar_url": "https://avatars2.githubusercontent.com/in/15368?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
    "html_url": "https://github.com/apps/github-actions",
    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
    "type": "Bot",
    "site_admin": false
  }
}
```

**Comment by FFY00** [comment]
Can't this be done from CircleCI instead of Github Actions? Wouldn't that fix the issue?

**Comment by bentiss** [comment]
> Are we sure it that job was generated by a PR?

yes, the error in the output is the one from github telling us that we can not create the commit status, the first curl which created the pipeline worked.

> Can't this be done from CircleCI instead of Github Actions? Wouldn't that fix the issue?

Yes, and no.

I wanted to use GH Actions to store the credentials on github, not on a third party dashboard, but that means a new CI syntax to learn

ANd no, the problem is to create the notification to github, and being called from github or circle CI doesn't change the fact that we are not calling the correct endpoint.

**Comment by FFY00** [comment]
@bentiss is this OK to merge? You enable the CI on PRs in #27.

**Comment by bentiss** [comment]
Right now, not sure. This triggers 2 jobs on the gitlabCI, and that is one too many.

I still need to get my head around this, but I am not sure we will end up keeping this kind of gitlab CI trigger from github. [Honestly, we probably better just switch this project over gitlab]

**Comment by FFY00** [comment]
Well, we can enable it now and disable it if we get any issues. I don't expect much noise here.

**Comment by bentiss** [comment]
maybe

**Pull request merged**
