### PR TITLE
ci: add circleci config

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@archlinux.org>

### CODE REVIEW

**Comment by bentiss** [comment]
Hmm, have you tried it actually? `pytest` creates `uhid` devices, so it need root access to `/dev/uhid`.
Unless you are using a VM, this is not safe in a container environment...

**Comment by FFY00** [comment]
You are right, we need to run a VM inside circleci.

**Comment by FFY00** [comment]
Closing this for now.

**Comment by bentiss** [comment]
Dumping some notes here:
- for being able to fully test this, we need a VM
- gitlab.freedesktop.org has a working environment for that: https://gitlab.freedesktop.org/wayland/ci-templates/merge_requests/6
- the gitlab/github integration is only available in premium gitlab, meaning we can't rely on this for the freedesktop instance
- we *could* use a push webhook from github to gitlab to mirror the repo and then use gitlab to send commit statuses through the github API
- this doesn't work much with PR as PR has an event for it, but the data is encapsulated in `HTTP_X_GITHUB_EVENT` and this gets lost if we simply trigger a pipeline from the gitlab API

Solutions seem always to involve running a service somewhere, which is something I do not want to maintain.

So, how about we still use circle CI, and have a special job on top of the containers capable tests that create a new local branch with the MR, add some references in a text file to know which status needs to be updated, pushes it to a gitlab fork of the project, and then we have a `gitlab-ci.yaml` script that creates a qemu, runs the tests and update the status.

Once we have this in place, we can duplicate this for libratbag too.

**Pull request closed without merging**
