### PR TITLE
Add initial circle CI

### PR DESCRIPTION
**Pull request by bentiss**
Just a simple flake8 run that gives us some statistic but fail for syntax error.

Note: I took the skeleton of the flake8 commands from the github actions template. Long term I  think we might want to switch to actions so we can put our gitlab API keys to run the full qemu tests in github itself instead of having to deal with CircleCI.

### CODE REVIEW

**Comment by bentiss** [comment]
FWIW, I just enabled circle-ci on libratbag/ratbag-emu

**Comment by FFY00** [comment]
Are you sure? Because I did that.

**Comment by bentiss** [comment]
well, it was not enabled in the libratbag organization, so I did, but we still do not see the badges.

**Comment by bentiss** [comment]
heh, according to the dashboard I beat you by 4 seconds

**Pull request merged**
