### PR TITLE
Class diagram

### PR DESCRIPTION
**Pull request by FFY00**

### CODE REVIEW

**Comment by FFY00** [comment]
I tried putting this in sphinx but sphinxcontrib-mermaid is not generating the diagrams properly.

**Comment by bentiss** [comment]
> I tried putting this in sphinx but sphinxcontrib-mermaid is not generating the diagrams properly.

to make gitlab renderer happy, I had to add a bunch of `sth` after the `Device-->>-Device:` when there was no data after

**Comment by FFY00** [comment]
Yes, I figured that and made the change locally when trying to get sphinx to work. I will commit it.

**Comment by FFY00** [comment]
Sphinx still doesn't work with that btw.

Here's a preview: https://pkgbuild.com/~ffy00/documentation/ratbag-emu-sphix-demo/design.html

**Comment by bentiss** [comment]
don't worry too much about that, either we add  a CI job that creates the magic snippet on gitlab, either we'll figure it out later :)

**Comment by bentiss** [comment]
I am pretty sure the arrows are inverted in the class diagram, the "inherits" arrow points at the super class, not the other way around. Not 100% sure for aggregations

**Comment by FFY00** [comment]
My local parse accepts just a space after the `:` in the sequence diagram but it seems gitlab is still not happy with that. Added "return" in those cases.

**Comment by bentiss** [comment]
> I am pretty sure the arrows are inverted in the class diagram, the "inherits" arrow points at the super class, not the other way around. Not 100% sure for aggregations

http://www.agilemodeling.com/artifacts/classDiagram.htm -> the inheritance and aggregations are inverted in your graph

**Comment by FFY00** [comment]
Okay, should be good now.

https://gitlab.freedesktop.org/snippets/842

**Comment by bentiss** [comment]
Sorry, I'm a PITA, but if we want to merge this, it needs to not have the bits of #48, and those bits should be added as part of #48 itself, so we can discuss about it.

**Comment by FFY00** [comment]
Nah, you're not a PITA. I started doing that locally but I figured it was porbably best to hear from you about the first commit before I rebased. Otherwise I would have to sync #48 on every change here.

Is the first commit fine?

**Comment by bentiss** [comment]
yes, I think it is.

Don't bother break the other changes in #48, just add a commit at the end. It won't break anything to not have the diagram in sync for every commit

**Review by bentiss — APPROVED** [review]
first commit is good, so you can merge it

**Comment by FFY00** [comment]
> Don't bother break the other changes in #48, just add a commit at the end. It won't break anything to not have the diagram in sync for every commit

It's easier for me to just rebase on top of this branch.

**Pull request merged**
